### ISSUE TITLE
Store page subresources in separate files

### ISSUE THREAD

**Issue by erikrose** [mozilla/fathom#102]
GitHub gets grumpy about us uploading >2GB git packs (i.e. it refuses), making it hard to share ruleset repos. Let's split page subresources (images, etc.) out and store them in git-lfs.

Pros:
+ Simple simple simple to use.
+ Versioned with code.
+ History-preserving
+ No 200MB file-size cap
+ Per-project permissions. No new ACLs to set up.

Cons:
- No diffs.

But, if we store the subresources in LFS and commit the markup to plain git, then we can diff it after all (and much faster than now), and the cons go to nil. git-lfs-migrate can even help automate this. LFS costs a little money but not enough to bother about at GitHub.

2 spot-checks measure 123x (on a 9.8MB sample) and 877x (on a 98MB sample) reductions in size by stripping images and other subresources out. (Files stored in LFS don't count toward your quota at GitHub.) That means we'll have room for about 10,000 samples, which should be plenty for the foreseeable future. If awesome RNN advances mean more than that is worthwhile to collect, I'll be thrilled to come up with a fancier solution at that point.

We'll need **a tool to extract subresources from existing samples** and **a plan for making them external on future ones**. I currently suspect we'll do the same freeze-and-extract dance on future ones, since otherwise we'll need some way of downloading multiple files from freeze-dry, like tarring them up, while still keeping all the files that go with one page together, in case we're using the bulk Corpus Collector.

**Comment by danielhertenstein** [comment]
I will start with the login-forms corpus.

**Comment by danielhertenstein** [comment]
@erikrose, what are we considering subresources? Anything that is a link out on the page normally?

**Comment by erikrose** [comment]
Anything currently inlined as a data URL: images, stylesheets, iframes, and so on

**Comment by danielhertenstein** [comment]
Do we care about converting the base64 strings back to their original formats after extracting them? If we're just going to compress them and stick them in LFS, I don't see a need to convert them.

**Comment by erikrose** [comment]
De-base-64-ing them is the only way I can think of to get the pages to load them again: just stick them in the (LFS'd) repo as images and tweak the HTML to reference them as normal files. Can you think of another way?

**Comment by danielhertenstein** [comment]
The other option is to require a person to run another script that will reinsert the base64 strings before they can load the page again. But it is simple enough to convert them so they can be referenced and I will go that route. I wanted to make sure we had a need for it before I continued down that path.

**Comment by erikrose** [comment]
Great. I suspect stopping inlining will also lessen the RAM load on Firefox (not that it matters since we're loading only 1 page at a time these days). It's unusual for a mere 75 tabs to send a 16GB machine into swap, but that's what always happened when I used the FathomFox trainer.

**Comment by danielhertenstein** [comment]
Picking up from the discussion in #109, there are two remaining problems:

1. Some pages have a `<base>` tag that breaks the local references that we're adding in
2. Some pages give CORS errors when trying to load their resources

To prevent new samples from having a `<base>` tag, we can update the version of freezeDry we are using as the newest version does not include that tag. This is already being worked on here: https://github.com/mozilla/fathom-fox/issues/34. However, we still have samples with existing `<base>` tags, so we'll need to get rid of them in our `fathom-extract` tool. @erikrose, do you think we should preserve the url from the `<base>` tag for any reason? The newest version of freezeDry includes the original url in a `<link>` in the `<head>` of the saved page. We could replicate that if we wanted to for those pages with `<base>` tags, though since the didn't seem to be useful it may not be worth the effort.

**Comment by erikrose** [comment]
The `<base>` tag doesn't really preserve the whole URL, just the…well…base. The last segment is omitted. So it's not really useful to preserve for our purposes. We have, up to now, kept spreadsheets off to the side with the URLs mapped to samples, so we can fall back on those if we need URLs to old samples. It'll be great to have the full URLs on new ones!

**Comment by danielhertenstein** [comment]
Closed by #117
