### ISSUE TITLE
Make `fathom-vectorize` and `fathom-train` one tool

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/fathom#175]
Right now, we explicitly pass the `vectors.json` files output by FathomFox's Vectorizer (and soon, hopefully, `fathom-vectorize`) as arguments to `fathom-train`.

It would be great if `fathom-vectorize` fed directly into `fathom-train`, so that the developer just needs to modify their ruleset and run a single command to get the new training results.

**Comment by danielhertenstein** [comment]
If a user wanted to look at their vectors using the future `fathom-historgram`, would they want to be forced to train their ruleset in order to obtain their vectors? I think this is a minor use case, but perhaps we should include a flag (like `--vectors_only` or `--no_train`) in the combined tool to cover the use case?

**Comment by erikrose** [comment]
Done in the big autovectorization feature of 3.4. fathom-histogram, if we land it, will autovectorize just like fathom-train and -test do (and take advantage of any cached vectorizations they've already done).
