### ISSUE TITLE
Configuring Vectorizer...Error: Couldn't find trainee ID "TRAINEE" in your rulesets.

### ISSUE THREAD

**Issue by reuben** [mozilla/fathom#263]
I thought it was related to installing from source, but it happens even if from a fresh environment, I run:

```
$ pip install fathom-web
$ npm install fathom-web
$ fathom train samples/folder/ --ruleset my_ruleset.js --trainee TRAINEE
```

...to get the packages setup. Loading the built add-on into the browser with `about:debugging` and going to the vectorizer page also shows an empty list of trainees.

**Comment by erikrose** [comment]
Hi, Reuben! I'm curious: what were you expecting to see in the list of trainees?

We used to have a fancy protocol wherein you could use the AMO-provided copy of FathomFox and then bundle your ruleset into a separate add-on and the two would talk. But this turned out to be more complicated that it was worth.

Today, vectorization should always be done automatically by tools like `fathom-train`. The only reason to use FathomFox with your own ruleset is the Evaluator. And the best way to launch that is with `fathom fox -r your_ruleset.js`. This also [takes care of putting you in a blank profile and tweaking a few other settings](https://mozilla.github.io/fathom/installing.html#fathomfox-installation).

Btw, you shouldn't have to `npm install fathom` unless you're writing a node.js app.

**Comment by reuben** [comment]
Sorry, I should have specified better. I see the error in the title when running `fathom train`, I was just experimenting with the AMO copy to try and find out if it was something I did wrong with the local source install.

And I did `npm install fathom-web`, not `fathom`, that was just a typo.

**Comment by reuben** [comment]
Specifically I'm doing `fathom train samples/folder/ --ruleset blah.js --trainee TRAINEE` and getting that error.

**Comment by erikrose** [comment]
Ah! Okay, then. Assuming your blah.js looks something like https://mozilla.github.io/fathom/example.html, what you'd want to pass to `--trainee` is whatever the key in the `trainees` map is. In my example, it's "overlay", as in in `trainees.set("overlay", …`. Does that fix the problem?

**Comment by reuben** [comment]
I am passing the same trainee name as is in the ruleset file. My suspicion is that the ruleset is not being installed at all with the add-on.

**Comment by reuben** [comment]
I think it's something wrong with my ruleset because using the example one verbatim works...

**Comment by erikrose** [comment]
Hmm, either the key isn't getting set in `trainees`, or there's no `export default trainees` at the bottom.

**Comment by erikrose** [comment]
(If you were making an outright syntax error, it would say so.)

**Comment by reuben** [comment]
What's the easiest way to find out if I have a syntax error in my ruleset? I only see "trainees is not defined" for the vectorizer page but it doesn't tell me much... It is defined and exported.

**Comment by reuben** [comment]
I think I figured it out... Once I changed

```js
import {ruleset, rule, dom, type, score, out} from 'fathom-web';
import {euclidean} from 'fathom-web/clusters';
```

to 

```js
import {ruleset, rule, dom, type, score, out, clusters} from 'fathom-web';
const {euclidean} = clusters;
```

Then it got past that stage.

**Comment by erikrose** [comment]
That makes sense. The whole FS-path-based import pattern common in node.js doesn't work in the world of ES6 modules, which is where you're living.
