### ISSUE TITLE
Undocumented dependency on jsdom 8.5.0

### ISSUE THREAD

**Issue by brightredchilli** [mozilla/fathom#73]
First of all, thanks for this amazing and well thought out library.

From reading the [jsdom docs](https://github.com/tmpvar/jsdom), it appears that there was an api update that broke compatibility with pre api 10 versions of jsdom.

Using the latest jsdom (11.2.0), I wasn't able to get the code at https://mozilla.github.io/fathom/using.html#rules-sides-and-flows to work. Moreover, even after tweaking it for the new api, it breaks unexpectedly when querying facts against a boundedruleset.

I haven't investigated it in detail but it appears to be breaking at lhs.js

```
const matches = ruleset.doc.querySelectorAll(this.selector);
```

where jsdom used to expose querySelectorAll directly. For completeness, this is my stacktrace:
```
Uncaught TypeError: ruleset.doc.querySelectorAll is not a function
    at DomLhs.fnodes (/Users/Ying/Code/sfpc/newspaper-headlines/node_modules/fathom-web/lhs.js:88:37)
    at InwardRule.results (/Users/Ying/Code/sfpc/newspaper-headlines/node_modules/fathom-web/ruleset.js:315:37)
    at BoundRuleset._execute (/Users/Ying/Code/sfpc/newspaper-headlines/node_modules/fathom-web/ruleset.js:215:31)
    at BoundRuleset.get (/Users/Ying/Code/sfpc/newspaper-headlines/node_modules/fathom-web/ruleset.js:129:40)
    at request (/Users/Ying/Code/sfpc/newspaper-headlines/index.js:30:21)
    at ReadStream.<anonymous> (/Users/Ying/Code/sfpc/newspaper-headlines/node_modules/cached-request/lib/cached-request.js:249:15)
    at emitNone (events.js:110:20)
    at ReadStream.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
fnodes @ VM255 lhs.js:88
results @ VM249 ruleset.js:315
_execute @ VM249 ruleset.js:215
get @ VM249 ruleset.js:129
request @ VM60 index.js:30
(anonymous) @ VM63 cached-request.js:249
emitNone @ VM27 events.js:110
emit @ VM27 events.js:207
endReadableNT @ VM52 _stream_readable.js:1047
_combinedTickCallback @ VM39 next_tick.js:102
_tickCallback @ VM39 next_tick.js:161
```

I'm using node v8.1.3.

I tried to see what the query might look like on latest jsdom, but ran into some issues. I'd be happy to elaborate on it further.

For now, I downgraded jsdom to 8.5.0. If this is documented somewhere already, sorry for the repost. Otherwise, I can make a PR to the README to specify the dependency.

**Comment by erikrose** [comment]
Thanks for letting me know! Fathom doesn't list jsdom as a dependency because it strictly isn't one: Fathom is happy to run against any DOM-compliant object. For instance, it's quite happy running against an in-browser native DOM, and it shouldn't bundle jsdom into any in-browser deployments. We do use jsdom in the tests, so that's where we declare it, in `devDependencies`.

I think the real answer is going to take the form of [switching to domino](https://github.com/mozilla/fathom/issues/34), which also has the advantage of not leaking. However, for the interrim, you might need to pass `jsdom.jsdom(...).window.document` to `against()`. I haven't tried it, but I'm guessing based on how https://github.com/tmpvar/jsdom#basic-usage looks. It appears that that's where they're not hiding their DOM-compliant object. If that does work and you're willing, I'd welcome a doc patch so other people don't run into trouble!

**Comment by brightredchilli** [comment]
Cool! This works:
```
// tested with fathom-web@2.1.0, jsdom@11.2.0
const body = new jsdom.JSDOM(htmlString).window.document
const facts = rules.against(body)
```

Where should I make this pr?

**Comment by brightredchilli** [comment]
Wow, it took me longer than it should have to understand what you were proposing. So this works perfectly using domino:

```
const body = domino.createDocument(htmlString, true)
const facts = rules.against(body)
```

I think perhaps the doc patch should switch to recommending this implementation for server side dom handling?

**Comment by erikrose** [comment]
I'd love to see us switch over to domino entirely. Toward that, I tried replacing staticDom() (our helper procedure for creating server-side DOMs for tests) with your implementation. However, it didn't pass all the tests:

```
  5 failing

  1) Cluster tests distance() considers A and B to be far apart if one contains the other:
     TypeError: Cannot read property 'parentNode' of null
      at distance (clusters.js:112:30)
      at Context.<anonymous> (test/clusters_tests.js:199:26)

  2) Cluster tests clusters() groups nearby similar nodes together:

      AssertionError: expected [ Array(1) ] to deeply equal [ Array(2) ]
      + expected - actual

       [
         [
      +    "G"
      +  ]
      +  [
      +    "E"
      +    "D"
           "F"
      -    "D"
      -    "E"
      +    "B"
      +    "A"
           "C"
      -    "A"
      -    "B"
      -    "G"
         ]
       ]

      at Context.<anonymous> (test/clusters_tests.js:260:20)

  3) Readability ruleset finds content from... large inner clusters with some piddly little text in their container:
     TypeError: Cannot read property 'parentNode' of null
      at distance (clusters.js:112:30)
      at clusters (lhs.js:311:23)
      at new DistanceMatrix (clusters.js:186:44)
      at clusters (clusters.js:314:20)
      at BestClusterLhs.fnodes (lhs.js:308:24)
      at OutwardRule.results (rule.js:287:69)
      at BoundRuleset._execute (ruleset.js:202:31)
      at BoundRuleset.get (ruleset.js:116:40)
      at contentFnodes (examples/readability.js:105:35)
      at snippetsFrom (test/readability_tests.js:17:36)
      at Context.<anonymous> (test/readability_tests.js:44:26)

  4) Readability ruleset finds content from... large outer clusters with some piddly inner things contained:

      AssertionError: expected [ Array(3) ] to deeply equal [ Array(3) ]
      + expected - actual

       [
      +  "Smoo bars."
         "Mangaroo. Witches an"
      -  "Smoo bars."
         "Bing bang, I saw the"
       ]

      at Context.<anonymous> (test/readability_tests.js:72:16)

  5) Ruleset takes a subtree of a document and operates on it:

      AssertionError: expected 'root' to equal 'inner'
      + expected - actual

      -root
      +inner

      at Context.<anonymous> (test/ruleset_tests.js:293:16)
```

2 and 4 might just be brittleness of tests—not real failures—but the other ones look legit. If you want to look into it, you're most welcome, and I'm happy to answer questions. Otherwise, we'd better keep recommending `jsdom` in the docs until domino works with all parts of Fathom.

**Comment by brightredchilli** [comment]
I'd be happy to, will take a look as soon as I can - but for now, the jsdom implementation as it stands in the fathom docs [here](https://mozilla.github.io/fathom/using.html#rules-sides-and-flows) does not work with jsdom@11.2.0. Maybe worth a quick patch there.
